//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_EF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public decimal Expenses { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
